name: Daily Ghibli Refresh
on:
  schedule:
    - cron: '0 15 * * *' 
  workflow_dispatch:      

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Push to TRMNL
        run: |
          IMAGE=$(ls *.jpg | shuf -n 1)
          echo "Sending $IMAGE to TRMNL..."
          
          # Use the NEW URL you just copied from the Webhook Image plugin
          curl -X POST "https://trmnl.com/api/plugin_settings/266c686a-405a-4824-8a82-5ba37e5aa5a6/image" \
               -H "Content-Type: image/jpeg" \
               --data-binary @"$IMAGE"
