name: Daily Ghibli Refresh
on:
  schedule:
    - cron: '0 15 * * *' 
  workflow_dispatch:      

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Push to TRMNL
        run: |
          IMAGE=$(ls *.jpg | shuf -n 1)
          B64=$(base64 -w 0 $IMAGE)
          curl -X POST "https://usetrmnl.com/api/custom_plugins/bf578f92-2df0-4fad-aece-f67a2b82aef" -H "Content-Type: application/json" -d "{\"merge_variables\":{\"ghibli_image\":\"data:image/jpeg;base64,$B64\"}}"
